modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="uraniummod"
version="1.0.0"
displayName="UraniumMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Zaxcu, MCreator"

[[dependencies.uraniummod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




